[normal]
q = "quit"
t = "tasks"
g = "global-tasks"
c = "new-task"
"ctrl-b" = "toggle-sidebar"
"ctrl-left" = "focus-sidebar"
"?" = "help"
":" = "command"
"ctrl-o" = "back"
"ctrl-i" = "forward"
"ctrl-k" = "palette"

[command]
escape = "normal"
enter = "execute-command"
