[normal]
q = "quit"
t = "tasks"
g = "global-tasks"
c = "new-task"
i = "inbox"
"ctrl-b" = "toggle-sidebar"
"?" = "help"
":" = "command"
"ctrl-o" = "back"
"ctrl-i" = "forward"

[command]
escape = "normal"
enter = "execute-command"
